apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: jenkins-slave-apic
  name: jenkins-slave-apic
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-slave-apic:latest
      namespace: openshift
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/abhinabsarkar/apiconnect-pipeline-jenkins-openshift/tree/master/src
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave:latest
        namespace: openshift
    type: Docker
  triggers:
  - github:
      secret: XXXXXXXXXXXXXXXXXX
    type: GitHub
  - generic:
      secret: XXXXXXXXXXXXXXXXXX
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
